language: java

addons:
  sonarcloud:
    organization: "grpc-swagger"
    token:
      secure: $SONAR_TOKEN

script:
  - sonar-scanner

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: grpc-swagger